config/routes.rb
Yanapana::Application.routes.draw do

    mount Spree::Core::Engine, :at => '/'

    Spree::Core::Engine.routes.prepend do
      namespace :admin do
        resources :artists do
        end
        resources :organizations do
        end
        resources :causes do
        end
	      resources :faqs do
          collection do
            post :sort
          end
        end
	      resources :teams do
        end
        resource :review_settings 
      end
      #match '/:week' => redirect('/'), :constraints => {:week => /week-[0-9]+/ }
      match '/week-:week' => "home#index"
      match "how-it-works" => "home#how_it_works", :as => :how_it_works
      match "dummy-confirm" => "home#dummy_confirm", :as => :dummy_confirm
      match "faq" => "home#faq", :as => :faq
      match "contact-us" => "home#contact_us", :as => :contact_us
      match "about-us" => "home#about_us", :as => :about_us
      match "dashboard" => "home#dashboard", :as => :dashboard
      match "subscribe" => "home#subscribe", :as => :subscribe
      match "landing" => "home#landing", :as => :landing
      match "partnership" => "home#partnership", :as => :partnership
      match "landing-newsletter" => "home#landing_newsletter", :as => :newsletter
      match "terms-and-conditions" => "home#terms_and_conditions", :as => :terms_and_conditions
      match "terms-and-conditions-artist" => "home#terms_and_conditions_artist", :as => :terms_and_conditions_artist
      match "without-causes" => "home#without_causes", :as => :without_causes
      match "preview-cause/:id" => "home#preview_cause", :as => :preview_cause
      match "preview-product/:id" => "products#preview_product", :as => :preview_product
      match "ordermailer" => "home#ordermailer", :as => :ordermailer
      match "artistmailer" => "home#artistmailer", :as => :artistmailer
      match "shipmentmailer" => "home#shipmentmailer", :as => :shipmentmailer
      match "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
      match "dashboard-organization" => "home#dashboard_organization", :as => :dashboard_organization
      #devise_for :user, :class_name => 'Spree::User', :controllers => {:invitations => 'devise/invitations'}
    end
end

app/models/spree/organization.rb
class Spree::Organization < ActiveRecord::Base
  has_many :causes
  accepts_nested_attributes_for :causes

  attr_accessible :contact, :country, :description, :email, :link_facebook, :link_twitter, :name, :phonenumber, :photo, :video, :webpage, :contact_name, :exemption_number, :contact_number, :address, :state, :city, :zip

  validates :name, :description, :contact, :contact_name, :contact_number, :webpage, :email, :contact, :address, :city, :state, :zip, :presence => true

  validates_attachment_presence :photo

  validates_attachment_content_type :photo,
    :content_type => ['image/jpg', 'image/png', 'image/jpeg'],
    :message => "must be jpg, png, jpeg"


  #Configurations Paperclip
  has_attached_file :photo,
    :styles => {:mini => "48x48>", :small=>"100x100>", :product=>"306x407>", :org =>"95x63>"},
    :storage => Rails.env == 'production' ? 's3' : 'filesystem',
    :s3_credentials => {
    :access_key_id => Spree::Config[:s3_access_key],
    :secret_access_key => Spree::Config[:s3_secret]
    },
    :bucket => Spree::Config[:s3_bucket]

    after_create :create_account

    def create_account
      Spree::User.invite!(:email=>self.email)
    end

end

app/controllers/spree/admin/organizations_controller.rb
class Spree::Admin::OrganizationsController < Spree::Admin::ResourceController

  def create
    @organization = Spree::Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to admin_organization_url(@organization), notice: 'Package was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/spree/admin/organizations_helper.rb
module Spree::Admin::OrganizationsHelper
end

app/views/spree/admin/organizations/_form.html.erb
<div class="left">
  <%= f.field_container :name do  %>
    <%= f.label :name %><span class="required">*</span><br />
    <%= f.text_field :name %>
  <% end %>

  <%= f.field_container :webpage do  %>
    <%= f.label :webpage %><span class="required">*</span><br />
    <%= f.text_field :webpage %>
  <% end %>

  <%= f.field_container :description do  %>
    <%= f.label :description %><span class="required">*</span><br />
    <%= f.text_area :description, :style => "height:50px" %>
  <% end %>

  <%= f.field_container :contact do  %>
    <%= f.label :contact, 'Contact person last name'%><span class="required">*</span><br />
    <%= f.text_field :contact %>
  <% end %>

  <%= f.field_container :contact_name do  %>
    <%= f.label :contact_name, 'Contact First name'%><span class="required">*</span><br />
    <%= f.text_field :contact_name %>
  <% end %>

  <%= f.field_container :email do  %>
    <%= f.label :email %><span class="required">*</span><br />
    <%= f.text_field :email %>
  <% end %>

  <%= f.field_container :contact_number do  %>
    <%= f.label :contact_number, 'Contact phone #'%><span class="required">*</span><br />
    <%= f.text_field :contact_number %>
  <% end %>

  <%= f.field_container :address do  %>
    <%= f.label :address, 'HQ Address' %><span class="required">*</span><br />
    <%= f.text_area :address, :style => "height:13px" %>
  <% end %>


</div>

<div class="right">
  <%= f.field_container :city do  %>
    <%= f.label :city %><span class="required">*</span><br />
    <%= f.text_field :city %>
  <% end %>

  <%= f.field_container :state do  %>
    <%= f.label :state %><span class="required">*</span><br />
    <%= f.text_field :state %>
  <% end %>

  <%= f.field_container :zip do  %>
    <%= f.label :zip %><span class="required">*</span><br />
    <%= f.text_field :zip %>
  <% end %>

  <%= f.field_container :country do  %>
    <%= f.label :country %><span class="required">*</span><br />
    <span id="bcountry">
      <%= f.collection_select(:country, Spree::Country.order("name ASC").all, :name, :name) %>
    </span>
  <% end %>

  <%= f.field_container :exemption_number do  %>
    <%= f.label :exemption_number, 'Exemption number'%><br />
    <%= f.text_field :exemption_number %>
  <% end %>

  <%= f.field_container :link_facebook do  %>
    <%= f.label :link_facebook%><br />
    <%= f.text_field :link_facebook %>
  <% end %>

  <%= f.field_container :link_twitter do  %>
    <%= f.label :link_twitter%><br />
    <%= f.text_field :link_twitter %>
  <% end %>

  <%= f.field_container :photo do  %>
    <%= f.label :photo, "Organization logo"%><span class="required">*</span><br />
    <%= f.file_field :photo %>
  <% end %>

</div>

app/views/spree/admin/organizations/edit.html.erb
<h1>Edit organization</h1>

<%= form_for [:admin, @organization], :html => {:multipart => true} do |f| %>

  <% if @organization.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error")%></h2>

      <ul>
        <% @organization.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button ("save") %> <%= link_to t('cancel'), admin_organization_url(@organization) %>
    </p>
<% end %>

app/views/spree/admin/organizations/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_product_link">
      <%= link_to '<span><img alt="Add" src="/assets/admin/icons/add.png">New Organization</span>'.html_safe, new_admin_organization_path, :class => "button"  %>
    </li>
  </ul>
</div>

<h1>Listing Organizations</h1>

<table class="index" id="listing_artists" data-hook>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Website</th>
    <th>Actions</th>
  </tr>

  <% @organizations.each do |organization|   %>
    <tr>
      <td><%= link_to organization.name, admin_organization_url(organization)  %></td>
      <td><%= organization.email  %></td>
      <td><%= organization.webpage  %></td>
      <td>
        <%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_organization_path(organization), :class=>"edit icon_link"  %>
        &nbsp;
        <%= link_to '<img alt="Delete" src="/assets/admin/icons/delete.png">Delete'.html_safe, admin_organization_path(organization), confirm: "Are you sure?", method: :delete  %>

      </td>
    </tr>


  <% end %>

</table>

app/views/spree/admin/organizations/new.html.erb
<h1>New Organization</h1>

<%= form_for [:admin, @organization], :html => {:multipart => true} do |f| %>

  <% if @organization.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error")%></h2>

      <ul>
        <% @organization.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button t("create") %> <%= link_to t('cancel'), collection_url %>
    </p>
<% end %>

app/views/spree/admin/organizations/show.html.erb
<h1><%= "Organization details:" %></h1>

  <p>
    <b>Name:</b>
    <%= @organization.name  %>
  </p>
  <p>
    <b>Webpage:</b>
    <%= @organization.webpage %>
  </p>
  <p>
    <b>Description:</b>
    <%= @organization.description %>
  </p>
  <p>
    <b>Contact Person last:</b>
    <%= @organization.contact  %>
    </p>
  <p>
  <p>
    <b>Contact First name:</b>
    <%= @organization.contact_name  %>
    </p>
  <p>
  <p>
    <b>Email:</b>
    <%= @organization.email  %>
    </p>
  <p>
    <b>Contact Phone #:</b>
    <%= @organization.contact_number%>
  </p>
  <p>
    <b>Contact HQ Address:</b>
    <%= @organization.address%>
  </p>
  <p>
    <b>City:</b>
    <%= @organization.city %>
  </p>
  <p>
    <b>State:</b>
    <%= @organization.state %>
  </p>
  <p>
    <b>Zip Code:</b>
    <%= @organization.zip %>
  </p>
  <p>
    <b>Country:</b>
    <%= @organization.country %>
  </p>
  <p>
    <b>Exemption number:</b>
    <%= @organization.exemption_number%>
  </p>
  <p>
    <b>Twitter:</b>
    <%= @organization.link_twitter  %>
  </p>
  <p>
    <b>Facebook:</b>
    <%= @organization.link_facebook %>
  </p>
  <p>
    <b>Photo:</b>
    <%= image_tag @organization.photo.url(:product) %>
  </p>

<%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_organization_path(@organization) %> |
<%= link_to 'Back', admin_organizations_path %>