config/routes.rb
Yanapana::Application.routes.draw do

    mount Spree::Core::Engine, :at => '/'

    Spree::Core::Engine.routes.prepend do
      namespace :admin do
        resources :artists do
        end
        resources :organizations do
        end
        resources :causes do
        end
	      resources :faqs do
          collection do
            post :sort
          end
        end
	      resources :teams do
        end
        resource :review_settings 
      end
      #match '/:week' => redirect('/'), :constraints => {:week => /week-[0-9]+/ }
      match '/week-:week' => "home#index"
      match "how-it-works" => "home#how_it_works", :as => :how_it_works
      match "dummy-confirm" => "home#dummy_confirm", :as => :dummy_confirm
      match "faq" => "home#faq", :as => :faq
      match "contact-us" => "home#contact_us", :as => :contact_us
      match "about-us" => "home#about_us", :as => :about_us
      match "dashboard" => "home#dashboard", :as => :dashboard
      match "subscribe" => "home#subscribe", :as => :subscribe
      match "landing" => "home#landing", :as => :landing
      match "partnership" => "home#partnership", :as => :partnership
      match "landing-newsletter" => "home#landing_newsletter", :as => :newsletter
      match "terms-and-conditions" => "home#terms_and_conditions", :as => :terms_and_conditions
      match "terms-and-conditions-artist" => "home#terms_and_conditions_artist", :as => :terms_and_conditions_artist
      match "without-causes" => "home#without_causes", :as => :without_causes
      match "preview-cause/:id" => "home#preview_cause", :as => :preview_cause
      match "preview-product/:id" => "products#preview_product", :as => :preview_product
      match "ordermailer" => "home#ordermailer", :as => :ordermailer
      match "artistmailer" => "home#artistmailer", :as => :artistmailer
      match "shipmentmailer" => "home#shipmentmailer", :as => :shipmentmailer
      match "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
      match "dashboard-organization" => "home#dashboard_organization", :as => :dashboard_organization
      #devise_for :user, :class_name => 'Spree::User', :controllers => {:invitations => 'devise/invitations'}
    end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/address.rb
module Spree
  class Address < ActiveRecord::Base
    belongs_to :country
    belongs_to :state

    has_many :shipments

    validates :firstname, :lastname, :address1, :city, :zipcode, :country, :presence => true
    validate :state_validate

    attr_accessible :firstname, :lastname, :address1, :address2,
                    :city, :zipcode, :country_id, :state_id,
                    :country, :state, :phone, :state_name,
                    :company, :alternative_phone

    # Disconnected since there's no code to display error messages yet OR matching client-side validation
    def phone_validate
      return if phone.blank?
      n_digits = phone.scan(/[0-9]/).size
      valid_chars = (phone =~ /^[-+()\/\s\d]+$/)
      errors.add :phone, :invalid unless (n_digits > 5 && valid_chars)
    end

    def self.default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new({:country => country}, :without_protection => true)
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name 
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at', 'order_id') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        :name => full_name,
        :address1 => address1,
        :address2 => address2,
        :city => city,
        :state => state_text,
        :zip => zipcode,
        :country => country.try(:iso),
        :phone => phone
      }
    end

    private

      def state_validate
        # Skip state validation without country (also required)
        # or when disabled by preference
        return if country.blank? || !Spree::Config[:address_requires_state]

        # ensure associated state belongs to country
        if state.present?
          if state.country == country
            self.state_name = nil #not required as we have a valid state and country combo
          else
            if state_name.present?
              self.state = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
        if state_name.present?
          if country.states.present?
            states = country.states.find_all_by_name_or_abbr(state_name)

            if states.size == 1
              self.state = states.first
              self.state_name = nil
            else
              errors.add(:state, :invalid)
            end
          end
        end

        # ensure at least one state field is populated
        errors.add :state, :blank if state.blank? && state_name.blank?
      end

  end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :text_home, :string, :default => 'a'
end

app/models/spree/artist.rb
class Spree::Artist < ActiveRecord::Base
  has_many :causes
  accepts_nested_attributes_for :causes

  attr_accessible :address, :date_of_birth, :email, :last_name, :link_facebook, :link_twitter, :name, :place, :telephone, :type_art, :webpage, :photo, :reason, :portfolio, :sex, :state, :city, :zip

  #validations
  validates :name, :last_name, :email, :date_of_birth, :sex, :reason, :webpage, :presence => true

  validates_attachment_presence :photo

  validates_attachment_content_type :photo,
  :content_type => ['image/jpg', 'image/png', 'image/jpeg'],
  :message => "must be jpg, png, jpeg"

  #Configurations Paperclip
  has_attached_file :photo,
    :styles => {:mini => "48x48>", :small=>"100x100>", :product=>"306x407!", :org =>"95x63!", :artist_products => "203x271!", :profile_artist => "217x262!"},
    :storage => Rails.env == 'production' ? 's3' : 'filesystem',
    :s3_credentials => {
    :access_key_id => Spree::Config[:s3_access_key],
    :secret_access_key => Spree::Config[:s3_secret]
    },
    :bucket => Spree::Config[:s3_bucket]

  after_create :create_account

  def create_account
    Spree::User.invite!(:email=>self.email)
  end

  def name_with_initial
    "#{name}. #{last_name}"
  end

end

app/models/spree/cause.rb
class Spree::Cause < ActiveRecord::Base
  require "addressable/uri"
  
  belongs_to :artist
  belongs_to :organization
  has_many :products
  attr_accessible :description, :goal_facebook, :goal_money, :goal_twitter, :goal_pinterest, :photo, :status, :title, :video, :artist_id, :organization_id, :date_start, :date_finish, :number_goal, :status, :inspiration, :sharephoto, :titleshare

  validates :title, :description, :organization_id, :goal_money, :goal_facebook, :goal_twitter, :number_goal, :presence => true

  validates :description, :length => {:minimum => 50}

  #validate :cause_id_when_active, :on => :create
  validates_attachment_presence :photo

  validates_attachment_content_type :photo,
    :content_type => ['image/jpg', 'image/png', 'image/jpeg'],
    :message => "must be jpg, png, jpeg"

  validates_attachment_content_type :photo,
    :content_type => ['image/jpg', 'image/jpeg'],
    :message => "must be jpg, jpeg"

#Configurations Paperclip
  has_attached_file :photo,
    :styles => {:small=>"100x100>", :product=>"240x240>", :share_photo => "200x200!"},
    :storage => Rails.env == 'production' ? 's3' : 'filesystem',
    :s3_credentials => {
    :access_key_id => Spree::Config[:s3_access_key],
    :secret_access_key => Spree::Config[:s3_secret]
    },
    :bucket => Spree::Config[:s3_bucket]
  has_attached_file :sharephoto,
    :styles => {:small=>"100x100>", :share_photo => "200x200!"},
    :storage => Rails.env == 'production' ? 's3' : 'filesystem',
    :s3_credentials => {
    :access_key_id => Spree::Config[:s3_access_key],
    :secret_access_key => Spree::Config[:s3_secret]
    },
    :bucket => Spree::Config[:s3_bucket]



before_save :youtube
before_update :youtube


 def youtube
  uri = Addressable::URI.parse(self.video)
  if uri.query_values
      self.video = uri.query_values["v"].to_s
  end
 end


  #def cause_id_when_active
  #  if self.status == true
  #    if Spree::Cause.where("status = ?", true).count > 0
  #      errors.add( :id, 'there is already an active cause')
  #    end
  #  end
  #end


  def self.per_week
    date_now = Date.today
    by_status = Spree::Cause.where("date_start <= ? AND date_finish <= ?", date_now, date_now).order('date_start ASC').first
  end

  def total_money
      products_per_cause = Spree::Product.where(:cause_id=>id)
      variantes = []
      products_per_cause.each do |prod|
        variantes << prod.variants_ids
      end
      lineitems_per_cause = Spree::Order.total_line_items(variantes)

      orders = Spree::Order.total_orders(lineitems_per_cause.map(&:order_id))
      total = 0.00
      orders.each do |order|
        total = order.item_total + total
      end

      return total
  end


end

app/models/spree/contact_form.rb
class Spree::ContactForm < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :suggestion
  attribute :phone
  attribute :message

  SUGGESTION = ['duda','quiero vender']

  class << self
    SUGGESTION.each do |suggestion|
      define_method "sugg_#{suggestion}" do
        subject
      end
    end
  end


  def headers
    {
      :subject => "My Contact Form",
      :to => "roberto.laraesp@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/spree/faq.rb
class Spree::Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :position
  acts_as_list


end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
		attr_accessible :chest, :waist, :lenght 
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  attr_accessible :cause_id, :inspiration_behind

  belongs_to :cause

  validate :cause_id, :presence => true

  before_save :save_date

  def variants_ids
    self.variants.map(&:id)
  end

  private

  def save_date
    self.available_on = self.cause.date_start
  end
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  devise :invitable

end

app/controllers/spree/admin/artists_controller.rb
class Spree::Admin::ArtistsController < Spree::Admin::ResourceController

  #Se usan los metodos de la gema spree (index,new,edit,delete,show)

end

app/controllers/spree/admin/causes_controller.rb
class Spree::Admin::CausesController < Spree::Admin::ResourceController

end

app/controllers/spree/admin/faqs_controller.rb
class Spree::Admin::FaqsController < Spree::Admin::ResourceController

  #Se usan los metodos de la gema spree (index,new,edit,delete,show)


  def sort
    params[:positions].each do |id, index|
    Spree::Faq.where(:id => id).update_all(:position => index)
    end

    respond_to do |format|
      format.html {redirect_to admin_faqs_url}
      format.js { render :text => 'Ok' }
    end

    #params[:faq].each_with_index do |id, index|
     # Spree::Faq.update_all({position: index+1}, {id: id})
    #end
    #render nothing: true
  end

end

app/controllers/spree/admin/organizations_controller.rb
class Spree::Admin::OrganizationsController < Spree::Admin::ResourceController

  def create
    @organization = Spree::Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to admin_organization_url(@organization), notice: 'Package was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_filter :check_json_authenticity, :only => :index
      before_filter :load_data, :except => :index
      create.before :create_before
      update.before :update_before

      def show
        redirect_to( :action => :edit )
      end

      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      def update
        if params[:product][:taxon_ids].present?
          params[:product][:taxon_ids] = params[:product][:taxon_ids].split(',')
        end
        super
      end

      def destroy
        @product = Product.where(:permalink => params[:id]).first!
        @product.delete

        flash.notice = I18n.t('notice_messages.product_deleted')

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.save
          flash.notice = I18n.t('notice_messages.product_cloned')
        else
          flash.notice = I18n.t('notice_messages.product_not_cloned')
        end

        respond_with(@new) { |format| format.html { redirect_to edit_admin_product_url(@new) } }
      end

      protected

        def find_resource
          Product.find_by_permalink!(params[:id])
        end

        def location_after_save
          edit_admin_product_url(@product)
        end

        # Allow different formats of json data to suit different ajax calls
        def json_data
          json_format = params[:json_format] or 'default'
          case json_format
           
										when 'basic'
            collection.map {|p| {'id' => p.id, 'name' => p.name}}.to_json
          else
            collection.to_json(:include => {:variants => {:include => {:option_values => {:include => :option_type},
                                                          :images => {:only => [:id], :methods => :mini_url}}},
                                                          :images => {:only => [:id], :methods => :mini_url}, :master => {}})
          end
        end

        def load_data
          @taxons = Taxon.order(:name)
          @option_types = OptionType.order(:name)
          @tax_categories = TaxCategory.order(:name)
          @shipping_categories = ShippingCategory.order(:name)
        end

        def collection
          return @collection if @collection.present?

          unless request.xhr?
            params[:q] ||= {}
            params[:q][:deleted_at_null] ||= "1"

            params[:q][:s] ||= "name asc"

            @search = super.ransack(params[:q])
            @collection = @search.result.
              group_by_products_id.             
														includes([:master, {:variants => [:images, :option_values]}]).
              page(params[:page]).
              per(Spree::Config[:admin_products_per_page])
														
              # PostgreSQL compatibility
              if params[:q][:s].include?("master_price")
                @collection = @collection.group("spree_variants.price")
														end
 													if params[:q][:s].include?("sku")
                
															if params[:q][:s].include?("desc")
                @collection = @collection.group("variants_spree_products.sku", "spree_variants.id", "variants_spree_products.id", "spree_assets.id", "spree_option_values.id").order("spree_variants.sku DESC")
															else
																@collection = @collection.group("variants_spree_products.sku", "spree_variants.id", "variants_spree_products.id", "spree_assets.id", "spree_option_values.id").order("spree_variants.sku ASC")
															end
														end
          else
            includes = [{:variants => [:images, {:option_values => :option_type}]}, {:master => :images}]

            @collection = super.where(["name #{LIKE} ?", "%#{params[:q]}%"])
            @collection = @collection.includes(includes).limit(params[:limit] || 10)
											
            tmp = super.where(["#{Variant.table_name}.sku #{LIKE} ?", "%#{params[:q]}%"])
            tmp = tmp.includes(:variants_including_master).limit(params[:limit] || 10)
            @collection.concat(tmp).uniq!
          end
          @collection
        end

        def create_before
          return if params[:product][:prototype_id].blank?
          @prototype = Spree::Prototype.find(params[:product][:prototype_id])
        end

        def update_before
          # note: we only reset the product properties if we're receiving a post from the form on that tab
          return unless params[:clear_product_properties]
          params[:product] ||= {}
        end
    end
  end
end

app/views/spree/layouts/_footer.html.erb
<div class="footer_container">
    <div class="footer_background"></div>
        <!--Footer Starts-->
        <footer>
            <ul class="footer_links">
                <li><span><%= link_to "Home", root_url %></span>
                    <ul class="hidden_movil">
                        <li><%= link_to "Cause", root_url + "#cause" %></li>
                        <li><%= link_to "Goals", root_url + "#goals" %></li>
                        <li><%= link_to "Products", root_url + "#products" %></li>
                        <li><%= link_to "Artist", root_url + "#artist" %></li>
                        <li><%= link_to "Comments", root_url + "#comments" %></li>
                    </ul>
                </li>
                <li><span><%= link_to "About Us", about_us_path %></span>
                    <ul class="hidden_movil">
                        <li><%= link_to "What is YANAPANA?", about_us_path + "#whowearw"%></li>
                        <li><%= link_to "Our Family", about_us_path + "#family"%></li>
                    </ul>
                </li>
                <li class="hidden_movil"> <span><%= link_to "Get Involved", how_it_works_path %> </span>
                    <ul class="hidden_movil">
                        <li><%= link_to "Submit Your Designs", how_it_works_path + "#submityourdesigns"%></li>
                        <li><%= link_to "Non-Profit Partnership", partnership_path %></li>
                    </ul>
                </li>

                <li class="hidden_desktop">
                    <span><%= link_to "Design for us", how_it_works_path%> </span>
                </li>

                <li class="hidden_desktop">
                    <span><%= link_to "Non-Profit Partnership", partnership_path  %> </span>
                </li>
                <li class="hidden_desktop">
                    <span><%= link_to "Blog", how_it_works_path %> </span>
                </li>
                <li><span><%= link_to "FAQ", faq_path %></span>
                    <ul class="hidden_movil">
                        <li><%= link_to "Contact Us", contact_us_path %></li>
                        <li><%= link_to "Terms and Conditiond of Returns", terms_and_conditions_path %></li>
                        <li><%= link_to "Privacy Policy", privacy_policy_path %></li>
                        <li><%= link_to "Shipping Information", faq_path %></li>
                    </ul>
                </li>

                <li> <span><%= link_to "Contact Us", contact_us_path %></span>
                    <ul class="hidden_movil">
                        <li><%= link_to "Suggestions", contact_us_path + "#leavemessage" %></li>
                        <li><%= link_to "Questions", contact_us_path + "#leavemessage" %></li>
                        <li><%= link_to "Work With Us", contact_us_path + "#leavemessage" %></li>
                    </ul>
                </li>
            </ul>
            <div class="footer_customblock">
                <div class="shipping_info">
                    <big>NOT BUYING TODAY?</big><br>
                    <small>No problem! You can always spread the word on social networks. </small>
                    <div id="social_media">
                        <div class="find_us">
                            <a class="facebook_white" href="http://www.facebook.com/YANAPANAcom?fref=ts"></a> <a class="twitter_white" href="https://twitter.com/yanapanawear"></a> <a class="pinterest_white" href="https://pinterest.com/yanapana"></a> </div>
                        </div>
                    </div>
                <div class="contact_info">
                    <big>Subscribe to our newsletter</big>
                    <div id="newsletter">
                      <%= form_tag subscribe_path, :remote => true, :html => {:id => 'sign-up'} do %>

                        <input  type="email" value="" placeholder="Your Email" id="email" name="email">
                        <input type="submit" value="Register" name="subscribe" class="sign-up sc-button light-blue">

                        <span class="form-Motivationessage" id="response"></span>

                      <% end %>
                    </div>

                                    </div>
            </div>
            <address>
                <h1 class="logo_footer"> <a href="#"><%= image_tag ("image-yanapana/logo_footer.png") %></a></h1>
                Copyright © 2013 YANAPANA. All Rights Reserved.
            </address>
        </footer>
        <!--Footer Ends-->
    </div>

app/views/spree/layouts/_head.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>YANAPANA</title>
<!--CSS-->
<%= stylesheet_link_tag 'store/all', :media => 'screen' %>
<!--Google Webfont -->
<link href='http://fonts.googleapis.com/css?family=Istok+Web' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="//use.typekit.net/xxr3kft.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<!--Javascript-->
  <%= javascript_include_tag "store/all" %>
<!--[if lt IE 9]>
    <script src="js/html5.js"></script>
<![endif]-->
<!-- mobile setting -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

app/views/spree/layouts/_header.html.erb
<div class="feedback positive" style="display:none">
  Thanks for adding me to your cart. :) 
</div>
<div class="feedback negative" style="display:none">The item you picked is out of stock ='(</div>
<header>
  <div class="top_bar clear">
    <!--Language Switcher Starts
    <div class="language_switch"><a class="active" href="#" title="ENGLISH">EN</a><a href="#" title="FRENCH">FR</a><a href="#" title="SPANISH">ES</a><a href="#" title="GERMAN">DE</a> </div>
    Language Switcher Ends-->

    <!--Top Links Starts-->
    <ul class="top_links">
      <% if current_user %>
        <% if Spree::Artist.find_by_email(current_user.email)%>
          <li><%= link_to "Dashboard", dashboard_path %></li>
        <% elsif Spree::Organization.find_by_email(current_user.email) %>
          <li><%= link_to "Organization account", dashboard_organization_path %></li>
        <% end %>
        <li><a><%= current_user.email %></a></li>
        <li><%= link_to "Logout", destroy_user_session_path %></li>
      <% end %>
      <li>
        <div class="minicart">
          <%= link_to "Cart", :class => "minicart_link" do %>
            <% if current_order%>
              <span class="item"><b><%= current_order.item_count %>
              </b><% if current_order.item_count > 1 %> ITEMS <% else %>ITEM <% end %>/</span> <span class="price"><b><%= current_order.display_total%></b>
              </span>
            <% else %>
              <span class="item"><b>Empty</b> ITEM /</span> <span class="price"><b>0</b></span>
            <% end %>
          <% end %>

          <div class="cart_drop" style="display:none">
            <span class="darw"></span>
            <ul>
            <% unless current_order.nil? or current_order.line_items.empty?%>
              <%= render :partial => 'spree/shared/preview_cart', :locals => { :current_order => current_order } %>
              <!--Validar que los productos sean de la causa que esta en curso -->
              <% current_order.line_items.each do |item|  %>
                <% unless @cause.nil? %>
                <% if @cause.id != item.variant.product.cause_id %>
                  <% current_order.empty! %>
                <% end %>
                <% end %>
              <% end %>
              <!--End -->
            <% else %>
                <div class="empty"> Your Shopping cart is empty!</div>
            <% end %>

            </ul>
          </div>

        </div>
      </li>
    </ul>
    <!--Top Links Ends-->
  </div>

  <!--Responsive NAV-->
  <div class="responsive-nav" style="display:none;">

  </div>
  <!--Responsive NAV-->

</header>

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
    <!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
      <!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
        <!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
<head>
  <%= render :partial => 'spree/layouts/head' %>
  <%= yield :head %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= yield :datos_sociales %>

</head>

<body>
  <div class="wrapper">
    <div class="header_container">
      <!--Header Starts-->
      <%= render :partial => 'spree/layouts/header' %>
    
    </div>
    
    <!--Branding Starts-->
    <div class="branding_container jean">
      <div class="branding_area">
        <!--Logo Starts-->
        <h1 class="logo"><%=link_to image_tag("image-yanapana/logo_header.png"), root_path%></h1>
        <!--Logo Ends-->
        <!--Countdown Starts-->
        <div id='open-until'></div>
        <!--Countdown Ends-->
      </div>
    </div>
    <!--Branding Ends-->
    <div class="navigation_container jean">
      <!--Navigation Starts-->
      <nav>
        <ul class="primary_nav">
            <li <%= 'class=active' if action_name == "index" %> > <%= link_to "Home", root_path %></li>

            <li<%= 'class=active' if action_name == "about_us" %>  ><%= link_to "About Us", about_us_path  %></li>

            <li  <%= 'class=active' if action_name == "how_it_works" || action_name == "partnership"%> ><%= link_to "Get involved", "#" %>
            <ul class="sub_menu">
              <li>
                <ul>
                  <li><%= link_to "Design For Us", how_it_works_path  %></li>
                  <li> <%= link_to "Non-Profit Partnership", partnership_path  %></li>
                </ul>
              </li>

            </ul>

            </li>
            <li><a href="http://yanapana.tumblr.com" target="_blank">Blog</a></li>

            <li  <%= 'class=active' if action_name == "faq" %> ><%= link_to "FAQ", faq_path  %></li>
<li  <%= 'class=active' if action_name == "contact_us" %> ><%= link_to "Contact Us", contact_us_path  %></li>
        </ul>
        <div id="social_media">
          <div class="find_us hidden_movil">
            <%= link_to '',  'http://facebook.com/YANAPANAwear?fref=ts', :class=>"facebook", :target=>"_blank"%> <%= link_to '', 'https://twitter.com/yanapanawear', :class=>"twitter", :target=>"_blank" %><%= link_to '', 'https://pinterest.com/yanapana', :class=>"pinterest", :target=>"_blank" %> </div>
        </div>

      </nav>
      <!--Navigation Ends-->
    </div>
    <% unless action_name == 'contact_us' || controller_name == 'products'%>
      <%= flash_messages %>
    <% end %>
    <%= yield %>
    <% yield :sidebar %>


  </div><!--End Wrapper-->


  <%= render :partial => 'spree/layouts/footer' %>
  <% @cause = Spree::Cause.where("date_start <= ? AND date_finish >= ?", Time.zone.now, Time.zone.now).order('date_start ASC').first %>
		<%= javascript_include_tag "jquery.countdown.min" %>
    <% unless @cause.nil? %>
      <script type="text/javascript" charset="utf-8">
    			$(document).ready(function(){
        var liftoffTime = new Date(<%= @cause.date_finish.to_i * 1000 %>);
        $("#open-until").countdown({until: liftoffTime, layout: "<%= escape_javascript(render :partial => 'spree/shared/countdown')%>", expiryUrl: "<%= root_url %>"
          });
       });
     </script>
  <% end %>
  <%= yield :javascripts %>

  </body>
</html>