config/routes.rb
Yanapana::Application.routes.draw do

    mount Spree::Core::Engine, :at => '/'

    Spree::Core::Engine.routes.prepend do
      namespace :admin do
        resources :artists do
        end
        resources :organizations do
        end
        resources :causes do
        end
	      resources :faqs do
          collection do
            post :sort
          end
        end
	      resources :teams do
        end
        resource :review_settings 
      end
      #match '/:week' => redirect('/'), :constraints => {:week => /week-[0-9]+/ }
      match '/week-:week' => "home#index"
      match "how-it-works" => "home#how_it_works", :as => :how_it_works
      match "dummy-confirm" => "home#dummy_confirm", :as => :dummy_confirm
      match "faq" => "home#faq", :as => :faq
      match "contact-us" => "home#contact_us", :as => :contact_us
      match "about-us" => "home#about_us", :as => :about_us
      match "dashboard" => "home#dashboard", :as => :dashboard
      match "subscribe" => "home#subscribe", :as => :subscribe
      match "landing" => "home#landing", :as => :landing
      match "partnership" => "home#partnership", :as => :partnership
      match "landing-newsletter" => "home#landing_newsletter", :as => :newsletter
      match "terms-and-conditions" => "home#terms_and_conditions", :as => :terms_and_conditions
      match "terms-and-conditions-artist" => "home#terms_and_conditions_artist", :as => :terms_and_conditions_artist
      match "without-causes" => "home#without_causes", :as => :without_causes
      match "preview-cause/:id" => "home#preview_cause", :as => :preview_cause
      match "preview-product/:id" => "products#preview_product", :as => :preview_product
      match "ordermailer" => "home#ordermailer", :as => :ordermailer
      match "artistmailer" => "home#artistmailer", :as => :artistmailer
      match "shipmentmailer" => "home#shipmentmailer", :as => :shipmentmailer
      match "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
      match "dashboard-organization" => "home#dashboard_organization", :as => :dashboard_organization
      #devise_for :user, :class_name => 'Spree::User', :controllers => {:invitations => 'devise/invitations'}
    end
end

app/models/spree/artist.rb
class Spree::Artist < ActiveRecord::Base
  has_many :causes
  accepts_nested_attributes_for :causes

  attr_accessible :address, :date_of_birth, :email, :last_name, :link_facebook, :link_twitter, :name, :place, :telephone, :type_art, :webpage, :photo, :reason, :portfolio, :sex, :state, :city, :zip

  #validations
  validates :name, :last_name, :email, :date_of_birth, :sex, :reason, :webpage, :presence => true

  validates_attachment_presence :photo

  validates_attachment_content_type :photo,
  :content_type => ['image/jpg', 'image/png', 'image/jpeg'],
  :message => "must be jpg, png, jpeg"

  #Configurations Paperclip
  has_attached_file :photo,
    :styles => {:mini => "48x48>", :small=>"100x100>", :product=>"306x407!", :org =>"95x63!", :artist_products => "203x271!", :profile_artist => "217x262!"},
    :storage => Rails.env == 'production' ? 's3' : 'filesystem',
    :s3_credentials => {
    :access_key_id => Spree::Config[:s3_access_key],
    :secret_access_key => Spree::Config[:s3_secret]
    },
    :bucket => Spree::Config[:s3_bucket]

  after_create :create_account

  def create_account
    Spree::User.invite!(:email=>self.email)
  end

  def name_with_initial
    "#{name}. #{last_name}"
  end

end

app/controllers/spree/admin/artists_controller.rb
class Spree::Admin::ArtistsController < Spree::Admin::ResourceController

  #Se usan los metodos de la gema spree (index,new,edit,delete,show)

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/spree/admin/artists/_form.html.erb
<div class="left">
  <%= f.field_container :last_name do  %>
    <%= f.label :last_name%><span class="required">*</span><br />
    <%= f.text_field :last_name %>
  <% end %>

  <%= f.field_container :name do  %>
    <%= f.label :name, 'First name'%><span class="required">*</span><br />
    <%= f.text_field :name %>
  <% end %>

  <%= f.field_container :date_of_birth do  %>
    <%= f.label :date_of_birth%><span class="required">*</span><br />
    <%= f.date_select :date_of_birth, :start_year => 1930, :end_year => 2012 %>
  <% end %>

  <%= f.field_container :sex do  %>
    <%= f.label :sex%> <span class="required">*</span><br />
    <%= f.radio_button :sex, "male" %>Male
    <%= f.radio_button :sex, "female" %>Female
  <% end %>

  <%= f.field_container :address do  %>
    <%= f.label :address%><br />
    <%= f.text_field :address %>
  <% end %>

  <%= f.field_container :city do  %>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  <% end %>

  <%= f.field_container :state do  %>
    <%= f.label :state%><br />
    <%= f.text_field :state %>
  <% end %>

  <%= f.field_container :zip do  %>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  <% end %>

  <%= f.field_container :place do  %>
    <%= f.label :place, 'Country'%><br />
    <span id="bcountry">
      <%= f.collection_select(:place, Spree::Country.order("name ASC").all, :id, :name) %>
    </span>
  <% end %>

    </div>

<div class="right">
  <%= f.field_container :email do  %>
    <%= f.label :email %><span class="required">*</span><br />
    <%= f.email_field :email %>
  <% end %>

  <%= f.field_container :telephone do  %>
    <%= f.label :telephone, 'Phone #' %><br />
    <%= f.text_field :telephone %>
  <% end %>

  <%= f.field_container :type_art do  %>
    <%= f.label :type_art, 'Type of art' %><br />
    <%= f.text_field :type_art %>
  <% end %>

  <%= f.field_container :webpage do  %>
    <%= f.label :webpage, "Website"%><span class="required">*</span><br />
    <%= f.text_field :webpage %>
  <% end %>


  <%= f.field_container :portfolio do  %>
    <%= f.label :portfolio %><br />
    <%= f.text_field :portfolio %>
  <% end %>

  <%= f.field_container :link_twitter do  %>
    <%= f.label :link_twitter%><br />
    <%= f.text_field :link_twitter %>
  <% end %>

  <%= f.field_container :link_facebook do  %>
    <%= f.label :link_facebook%><br />
    <%= f.text_field :link_facebook %>
  <% end %>

    <%= f.field_container :photo do  %>
    <%= f.label :photo%><span class="required">*</span><br />
    <%= f.file_field :photo %>
  <% end %>

  <%= f.field_container :reason do  %>
    <%= f.label :reason, 'Reason to design for Yanapana' %><span class="required">*</span><br />
    <%= f.text_area :reason, :style => "height:50px" %>
  <% end %>

</div>

app/views/spree/admin/artists/edit.html.erb
<h1>Edit artist</h1>

<%= form_for [:admin, @artist], :html => {:multipart => true} do |f| %>

  <% if @artist.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error")%></h2>

      <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button ("Save") %> <%= link_to t('cancel'), admin_artist_url(@artist) %>
    </p>
<% end %>

app/views/spree/admin/artists/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_product_link">
      <%= link_to '<span><img alt="Add" src="/assets/admin/icons/add.png">New Artist</span>'.html_safe, new_admin_artist_path, :class => "button"  %>
    </li>
  </ul>
</div>

<h1>Listing Artists</h1>

<table class="index" id="listing_artists" data-hook>
  <tr>
    <th>Lastname</th>
    <th>Name</th>
    <th>Email</th>
    <th>Webpage</th>
    <th>Actions</th>
  </tr>

  <% @artists.each do |artist|   %>
    <tr>
      <td><%= artist.last_name  %></td>
      <td><%= link_to artist.name, admin_artist_url(artist)  %></td>
      <td><%= artist.email  %></td>
      <td><%= artist.webpage  %></td>
      <td>
        <%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_artist_path(artist), :class=>"edit icon_link"  %>
        &nbsp;
        <%= link_to '<img alt="Delete" src="/assets/admin/icons/delete.png">Delete'.html_safe, admin_artist_path(artist), confirm: "Are you sure?", method: :delete  %>

      </td>
    </tr>


  <% end %>

</table>

app/views/spree/admin/artists/new.html.erb
<h1>New artist</h1>

<%= form_for [:admin, @artist], :html => {:multipart => true} do |f| %>

  <% if @artist.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error")%></h2>

      <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button t("create") %> <%= link_to t('cancel'), collection_url %>
    </p>
<% end %>

app/views/spree/admin/artists/show.html.erb
<h1><%= "Artist details:" %></h1>
  <p>
    <b>Last name:</b>
    <%= @artist.last_name  %>
  </p>
  <p>
    <b>Name:</b>
    <%= @artist.name  %>
  </p>
  <p>
    <b>Date of Birth:</b>
    <%= @artist.date_of_birth %>
  </p>
  <p>
    <b>Sex:</b>
    <%= @artist.sex  %>
  </p>
  <p>
    <b>Address:</b>
    <%= @artist.address  %>
  </p>
  <p>
    <b>City:</b>
    <%= @artist.city  %>
  </p>
  <p>
    <b>State:</b>
    <%= @artist.state %>
  </p>
  <p>
    <b>Zip:</b>
    <%= @artist.zip  %>
  </p>
  <p>
    <b>Country:</b>
    <%= @artist.place  %>
  </p>
  <p>
    <b>Phone #:</b>
    <%= @artist.telephone %>
  </p>
  <p>
    <b>Email:</b>
    <%= @artist.email  %>
  </p>
  <p>
    <b>Type Art:</b>
    <%= @artist.type_art  %>
  </p>
  <p>
    <b>Webpage:</b>
    <%= @artist.webpage  %>
  </p>
  <p>
    <b>Portfolio:</b>
    <%= @artist.portfolio %>
  </p>
  <p>
    <b>Twitter:</b>
    <%= @artist.link_twitter  %>
  </p>
  <p>
    <b>Facebook:</b>
    <%= @artist.link_facebook %>
  </p>
  <p>
    <b>Photo:</b>
    <%= image_tag @artist.photo.url(:product) %>
  </p>
  <p>
    <b>Reason:</b>
    <%= @artist.reason %>
  </p>

<%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_artist_path(@artist) %> |
<%= link_to 'Back', admin_artists_path %>