config/routes.rb
Yanapana::Application.routes.draw do

    mount Spree::Core::Engine, :at => '/'

    Spree::Core::Engine.routes.prepend do
      namespace :admin do
        resources :artists do
        end
        resources :organizations do
        end
        resources :causes do
        end
	      resources :faqs do
          collection do
            post :sort
          end
        end
	      resources :teams do
        end
        resource :review_settings 
      end
      #match '/:week' => redirect('/'), :constraints => {:week => /week-[0-9]+/ }
      match '/week-:week' => "home#index"
      match "how-it-works" => "home#how_it_works", :as => :how_it_works
      match "dummy-confirm" => "home#dummy_confirm", :as => :dummy_confirm
      match "faq" => "home#faq", :as => :faq
      match "contact-us" => "home#contact_us", :as => :contact_us
      match "about-us" => "home#about_us", :as => :about_us
      match "dashboard" => "home#dashboard", :as => :dashboard
      match "subscribe" => "home#subscribe", :as => :subscribe
      match "landing" => "home#landing", :as => :landing
      match "partnership" => "home#partnership", :as => :partnership
      match "landing-newsletter" => "home#landing_newsletter", :as => :newsletter
      match "terms-and-conditions" => "home#terms_and_conditions", :as => :terms_and_conditions
      match "terms-and-conditions-artist" => "home#terms_and_conditions_artist", :as => :terms_and_conditions_artist
      match "without-causes" => "home#without_causes", :as => :without_causes
      match "preview-cause/:id" => "home#preview_cause", :as => :preview_cause
      match "preview-product/:id" => "products#preview_product", :as => :preview_product
      match "ordermailer" => "home#ordermailer", :as => :ordermailer
      match "artistmailer" => "home#artistmailer", :as => :artistmailer
      match "shipmentmailer" => "home#shipmentmailer", :as => :shipmentmailer
      match "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
      match "dashboard-organization" => "home#dashboard_organization", :as => :dashboard_organization
      #devise_for :user, :class_name => 'Spree::User', :controllers => {:invitations => 'devise/invitations'}
    end
end

app/models/spree/faq.rb
class Spree::Faq < ActiveRecord::Base
  attr_accessible :answer, :question, :position
  acts_as_list


end

app/controllers/spree/admin/faqs_controller.rb
class Spree::Admin::FaqsController < Spree::Admin::ResourceController

  #Se usan los metodos de la gema spree (index,new,edit,delete,show)


  def sort
    params[:positions].each do |id, index|
    Spree::Faq.where(:id => id).update_all(:position => index)
    end

    respond_to do |format|
      format.html {redirect_to admin_faqs_url}
      format.js { render :text => 'Ok' }
    end

    #params[:faq].each_with_index do |id, index|
     # Spree::Faq.update_all({position: index+1}, {id: id})
    #end
    #render nothing: true
  end

end

app/views/spree/admin/faqs/_form.html.erb
<div class="left">
  <%= f.field_container :question do  %>
    <%= f.label :question %><span class="required">*</span><br />
    <%= f.text_field :question %>
  <% end %>

  <%= f.field_container :answer do  %>
    <%= f.label :answer %><span class="required">*</span><br />
    <%= f.text_area :answer %>
  <% end %>

</div>

app/views/spree/admin/faqs/edit.html.erb
<h1>Edit Faq</h1>

<%= form_for [:admin, @faq], :html => {:multipart => true} do |f| %>

  <% if @faq.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error")%></h2>

      <ul>
        <% @faq.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button ("Save") %> <%= link_to t('cancel'), admin_artist_url(@faq) %>
    </p>
<% end %>

app/views/spree/admin/faqs/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_product_link">
      <%= link_to '<span><img alt="Add" src="/assets/admin/icons/add.png">New Faq</span>'.html_safe, new_admin_faq_path, :class => "button"  %>
    </li>
  </ul>
</div>

<h1>Listing Faqs</h1>

<table class="index sortable" id="listing_faqs" data-hook data-sortable-link="faqs/sort">

  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th>Actions</th>
  </tr>

  <% @faqs.order('position ASC').each do |faq|   %>
    <tr class="spree_faq" id="<%=spree_dom_id faq%>" data-hook="option_row">
      <td><span class="handle"></span><%= faq.question  %></td>
      <td><%= faq.answer %></td>
      <td>
        <%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_faq_path(faq), :class=>"edit icon_link"  %>
        &nbsp;
        <%= link_to '<img alt="Delete" src="/assets/admin/icons/delete.png">Delete'.html_safe, admin_faq_path(faq), confirm: "Are you sure?", method: :delete  %>

      </td>
    </tr>


  <% end %>

</table>

app/views/spree/admin/faqs/new.html.erb
<h1>New Faq</h1>

<%= form_for [:admin, @faq], :html => {:multipart => true} do |f| %>

  <% if @faq.errors.any?  %>
    <div id ="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error")%></h2>

      <ul>
        <% @faq.errors.full_messages.each do |msg| %>
          <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'form', :locals => {:f => f} %>
    <p>
      <%= button t("create") %> <%= link_to t('cancel'), collection_url %>
    </p>
<% end %>

app/views/spree/admin/faqs/show.html.erb
<h1><%= "Faq details:" %></h1>
  <p>
    <b>Question:</b>
    <%= @faq.question  %>
  </p>
  <p>
    <b>Answer:</b>
    <%= @faq.answer  %>
  </p>
  
<%= link_to '<img alt="Edit" src="/assets/admin/icons/edit.png">Edit'.html_safe, edit_admin_faq_path(@faq) %> |
<%= link_to 'Back', admin_faqs_path %>